version: '3.7'
services:
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - ./docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass